services:
  simple-api:
    image: jkaninda/simple-api:latest
    restart: unless-stopped
    environment: &simple_api_env
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_TIMEOUT=60000
      - SPRING_DATA_REDIS_PASSWORD=password
      - RUN_DATA_SEED=true
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/internal/health/live || exit 1
  redis:
    image: redis:alpine
    restart: unless-stopped
    environment: *simple_api_env
    command: redis-server --appendonly yes --requirepass "${SPRING_DATA_REDIS_PASSWORD}"
    volumes:
      - ./redis:/data
  prometheus:
    image: prom/prometheus:v2.52.0
    restart: unless-stopped
    depends_on:
      simple-api:
        condition: service_started
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:11.0.0
    restart: unless-stopped
    depends_on:
      simple-api:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./config/api_nginx.conf:/etc/nginx/conf.d/api_nginx.conf
        - ./config/grafana_nginx.conf:/etc/nginx/conf.d/grafana_nginx.conf
