services:
  simple-api:
    image: jkaninda/simple-api:latest
    restart: unless-stopped
    environment: &simple_api_env
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_TIMEOUT=60000
      - SPRING_DATA_REDIS_PASSWORD=password
      - RUN_DATA_SEED=true
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/internal/health/live || exit 1
  redis:
    image: redis:alpine
    restart: unless-stopped
    environment: *simple_api_env
    command: redis-server --appendonly yes --requirepass "${SPRING_DATA_REDIS_PASSWORD}"
    volumes:
      - ./redis:/data
