global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "simple-api"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["simple-api:8080"]
        labels:
          application: 'Simple API'
